config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :categories
  resources :bookmarks
  root 'bookmarks#index'

  get "api/category/:id", to: "categories#api"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :category
  belongs_to :type
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories, class_name: "Category", foreign_key: "category_id", dependent: :destroy
  belongs_to :main_category, class_name: "Category", foreign_key: "category_id", optional: true

  has_many :bookmarks

end

app/models/type.rb
class Type < ApplicationRecord
    validates :title, presence: true
    has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
    @types = Type.all
    @categories = Category.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end


  def create
    @bookmark = Bookmark.new(bookmark_params)
    respond_to do |format|
      if @bookmark.save 
        format.js { render nothing: true, notice: 'Marca creada.' }
      else
        format.html { redirect_to root_path, alert: "boo" }
      end
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    @types = Type.all
    @categories = Category.all
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    respond_to do |format|
      if @bookmark.update(bookmark_params) 
        format.js { }
      else
        format.html { redirect_to root_path, alert: "boo" }
      end
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    respond_to do |format|
      if @bookmark.destroy! 
        format.js { }
      else
        format.html { redirect_to root_path, alert: "boo" }
      end
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url, :category_id, :type_id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    
    respond_to do |format|
      if @category.save 
        format.html { redirect_to categories_path, notice: "categoria creada" }
      else
        format.html { redirect_to categories_path, notice: "categoria no creada" }
      end
    end
  end

  def update 
    @category = Category.find(params[:id])
    # @category.public = @category.subcategories.public
    respond_to do |f|
      if @category.update!(categry_params) 
        f.html { redirect_to root_path, notice: "creaste"}
      else
        f.html { redirect_to root_path, alert: "boo"}
      end
    end
  end

  def api
    @category = Category.find(params[:id])
    render json: @category.to_json(include: [:sub_categories, :bookmarks])
  end

  private

  def category_params
    params.require(:category).permit(:title, :public, :category_id)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @type = Type.new
    @types = Type.all
    @bookmarks = Bookmark.all
  end

  def create
    @type = Type.new(type_params)
    
    respond_to do |format|
      if @type.save 
        format.html { redirect_to root_path, notice: "tipo creado" }
      else
        format.html { redirect_to root_path, notice: "tipo no creado" }
      end
    end
  end

  private

  def type_params
    params.require(:type).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/bookmarks/_bookmark.html.erb
<tr id="bookmark-<%= bookmark.id %>">
    <td><%= bookmark.id %></td>
    <td><%= bookmark.url %></td>
    <td><%= bookmark.category.title %></td>
    <td><%= bookmark.type.title %></td>
    <td><%= link_to 'Show', bookmark, remote: true %></td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark), remote: true %></td>
    <td><%= link_to 'Destroy', bookmark, method: :delete, remote: true, data: { confirm: 'seguro?' } %></td>
</tr>

app/views/bookmarks/_form.html.erb
<%= form_with(model: @bookmark, remote: true) do |f| %>
    <% if @bookmark.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este tipo no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @bookmark.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-group' %>
    </div>

    <div class="field">
        <%= f.label :type_id %>
        <%= f.collection_select :type_id, @types, :id, :title %>
    </div>

    <div class="field">
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, @categories, :id, :title %>
    </div>

    <div class = 'actions'>
        <%= f.submit %>
    </div>


<% end %>

app/views/bookmarks/create.js.erb
$("#bookmark-table").append('<%= j render(@bookmark, bookmark: @bookmark)%>');
$("#bookmark_form").hide();
$("#bookmark_buton").show()

app/views/bookmarks/destroy.js.erb
$("#bookmark-<%= @bookmark.id %>").empty()

app/views/bookmarks/edit.js.erb
$('#bookmark-form').html('<%= j render('bookmarks/form') %>');
$('#bookmark-button').hide();

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

<div id="bookmark-form"></div>

<div id="bookmark-button">
    <%= link_to 'Nuevo Bookmark', new_bookmark_path, class: 'btn btn-success', remote: true %>
</div>

<div id="bookmark-show"></div> 

<table class="table table-striped table-bordered table-hover text-center">
    <thead>
        <tr>
            <th>id</th>
            <th>URL</th>
            <th>Categoría</th>
            <th>Tipo</th>
        </tr>
    </thead>

    <tbody id="bookmark-table">
        <% @bookmarks.each do |bookmark| %>
        <tr id="bookmark-<%= bookmark.id %>">
            <td><%= bookmark.id %></td>
            <td><%= bookmark.url %></td>
            <td><%= bookmark.category.title %></td>
            <td><%= bookmark.type.title %></td>
            <td><%= link_to 'Show', bookmark, remote: true %></td>
            <td><%= link_to 'Edit', edit_bookmark_path(bookmark), remote: true %></td>
            <td><%= link_to 'Destroy', bookmark, method: :delete, remote: true, data: { confirm: 'seguro?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>    

app/views/bookmarks/new.js.erb
$('#bookmark-form').html('<%= j render('bookmarks/form') %>');
$('#bookmark-button').hide();

app/views/bookmarks/show.js.erb
$('#bookmark-show').html('<%= j render(@bookmark, bookmark: @bookmark)%>');

app/views/bookmarks/update.js.erb
$("#bookmark_form").html(" ")
$("#bookmark-<%= @bookmark.id %>").replaceWith('<%= j render(@bookmark, bookmark: @bookmark)%>')

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |f| %>
    <% if @category.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este tipo no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @category.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-group' %>
    </div>

    <div class="form-group">
        <%= f.label :public %>
        <%= f.check_box :public, class: 'form-group' %>
    </div>

    <div class="form-group">
        <%= f.label :category_id %>
        <%= f.select :category_id, options_from_collection_for_select(@categories, 'id', 'title', '0'), include_blank: true, class: 'form-group' %>
    </div>

    <div class = 'actions'>
        <%= f.submit %>
    </div>


<% end %>

app/views/categories/index.html.erb
<%= render 'form', category: @category %>

<h1>Categorias</h1>

    <table class="table table-striped table-bordered table-hover text-center">
        <thead>
            <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Public</th>
            <th>ID Padre</th>
            </tr>
        </thead>

        <tbody>
            <% @categories.each do |category| %>
            <tr>
                <td><%= category.id %></td>
                <td><%= category.title %></td>
                <td><%= category.public %></td>
                <td><%= category.category_id %></td>
            </tr>
            <% end %>
        </tbody>
    </table>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba JS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/types/_form.html.erb
<%= form_with(model: @type, local: true) do |f| %>
    <% if @type.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este tipo no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @type.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-group' %>
    </div>


    <div class = 'actions'>
        <%= f.submit %>
    </div>

<% end %>

app/views/types/index.html.erb
<%= render 'form', type: @type %>

<h1>Tipos</h1>

<table class="table table-striped table-bordered table-hover text-center">
    <thead>
        <tr>
        <th>Title</th>
        <th>Title</th>
        </tr>
    </thead>

    <tbody>
        <% @types.each do |type| %>
        <tr>
            <td><%= type.id %></td>
            <td><%= type.title %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= pie_chart @bookmarks.group("type_id").count %>